(()=>{'use strict';const $=s=>document.querySelector(s),config=window.INVITATION_CONFIG||{},reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const music=$('#music'),musicToggle=$('#music-toggle');music.volume=.6;function syncMusic(){musicToggle.setAttribute('aria-pressed',String(!music.paused));musicToggle.setAttribute('aria-label',music.paused?'Музыканы қосу':'Музыканы тоқтату');musicToggle.classList.toggle('playing',!music.paused)}music.addEventListener('play',syncMusic);music.addEventListener('pause',syncMusic);musicToggle.addEventListener('click',()=>{if(music.paused)music.play().catch(syncMusic);else music.pause()});const entry=$('#entry'),open=$('#open');open.addEventListener('click',()=>{if(entry.classList.contains('opened'))return;entry.classList.add('opened');musicToggle.hidden=false;music.play().catch(syncMusic);open.disabled=true;setTimeout(()=>{entry.hidden=true;document.documentElement.classList.remove('invitation-closed')},reduce?0:1550)});
// Reveal once and keep content in normal flow; no scroll-height changes or reversible opacity.
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){e.target.classList.add('arrived');observer.unobserve(e.target)}}},{threshold:.15});document.querySelectorAll('.reveal,.venue-scene').forEach(e=>observer.observe(e));
const modal=$('#reminder');$('#map-trigger').addEventListener('click',e=>{e.preventDefault();modal.showModal()});$('#close-reminder').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});$('#map-continue').addEventListener('click',()=>modal.close());$('#go-rsvp').addEventListener('click',()=>{modal.close();requestAnimationFrame(()=>requestAnimationFrame(()=>$('#rsvp').scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})))});
// Confirmed start: 15 November 2026, 17:00 Almaty (UTC+05:00).
const target=Date.parse('2026-11-15T17:00:00+05:00');
function updateCountdown(){let remaining=Math.max(0,Math.floor((target-Date.now())/1000));const values=[Math.floor(remaining/86400),Math.floor(remaining/3600)%24,Math.floor(remaining/60)%60,remaining%60];['days','hours','minutes','seconds'].forEach((key,i)=>$('#'+key).textContent=String(values[i]).padStart(2,'0'))}updateCountdown();setInterval(updateCountdown,1000);
const form=$('#rsvp-form'),status=$('#response');let busy=false,id;form.addEventListener('input',()=>{id=null});form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!form.reportValidity())return;const data=new FormData(form),name=String(data.get('name')||'').trim();if(!name){$('#guest-name').focus();return}if(!config.rsvpEndpoint){status.textContent='Жауап қабылдау әлі қосылған жоқ. Кейінірек қайта көріңіз.';return}busy=true;const button=form.querySelector('button');button.disabled=true;button.textContent='Жіберілуде…';status.textContent='';id=id||crypto.randomUUID();const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(config.rsvpEndpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({id,name,attendance:data.get('attendance'),eventId:config.eventId}),signal:controller.signal});const result=await r.json();if(!r.ok||!result.ok||result.id!==id)throw new Error('Response not confirmed');status.textContent='Рақмет! Жауабыңыз қабылданды.';button.textContent='Жауап қабылданды';}catch{status.textContent='Жауап жіберілмеді. Интернетті тексеріп, қайта көріңіз.';button.textContent='Қайта жіберу';button.disabled=false;}finally{clearTimeout(timeout);busy=false}});
})();
